# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QPdi27YF+xbirUQhU8hu3ffOh1grqpfdGL5pgK0CsEI79beCt6oOcUQNeFTbWkAMp5nW6A+P6PriqXw1vm1VuOobkWOsJ8gTrGrSa7FeneAbbnvQeagFxw98Ffu2yum5d+QWy42bpO9oISQFjPlwapHR0ecq4e9WJ43OOh/j/ee0sSKHD/qmZTxVGdV1x0G6N5iY1RL0TFBiYSqMz8vu89ciFB9dxL/DkSnTfUhf0QwmZTF/uef+x2EIq9p4uKC1Hp7G9bJzYiWTZIUroOhu1iRzCFI4H0kCd/AgCTwmlbNSZBBgho2bYaxExDfmI1moVVU4dNj+mWzTNcmz6iPjGXIRW5uREn0BciZHpNTae3lPfFfwGJtUi14S/B1SKg6dnogV6kVgU6rTHu32XgeapLJ/btRyAvw/7l/bpnrypFc0xODfF64bpyjE9pdd8zA4uF4fwEr2P0feiesk//h0k47XRPPJvFgNhHdIiA09skoAlX6UmKHTZjCe9DyOccwIDd37I31k8uiir6bvEcyBGe8JYJI9Meztw2AoUFPc+KVe78gFFRtXMJa2OgI7Z0hp09Vlnv9xV3QT2i5YOhvRyIaEoiqLG59YrP5Ir8LB/hV7cNmk15mnTOWqAIsHmcIjZQCElcsQe1uzHmmAwfVsh4jL3MXF01iYc0cRsAGuAc8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
