appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: IAREctI13bZ/b12B6jdiySUHkHGF938ePvOhx66eWPMgOjRhglNFONVhxYk24RLX3ldBZ0SijNxb06duaUvKZ6D4c56d9s6np2HwISx1aYIciDZSeOYd2nKKPO+ZV6b1RgngZ9zhpT8MoR2cMGA/0+i4UsMsfGJHZVlmclt1H+rDcPTpijP9QIsYQFKdFDVKKSHakRg8z4Ns1PLvcUfzK6pl0qi6Ic4ix7L0mvIc36pRaFOffU6MypoKP0xteGTBh7UZJwRdKBqWpUsvjsCb8Uzga7tsSiU9V/MIYazALBbE3oA1j6bIqgpK8B+xzLyvLd8hYISu16ROxK2go6QbiepDMf838NBeu9qsLFajhcQeihVwe1HaxSxq+/W4E8tm5/Sz7WOkSzLKjsVFI9AfxwdcxKbXtEQB0xGhWUbs5mr9+PdTEbsHthW4RrYYmzTamhHUAAyJSe8bcATSLP/E1Vg+SB2rv/deJTvjJMvDn5hOFf2zVMZz63tDd0x0iI24O3Ms3Pi2oxmRWl+UOFaVGJPxdlKOPgL0TH5jLKutn1eVIw59JjRmZKGjzyOS/gPElSsktFjFfn2YXv0aMVlduCtQZeppV7CSG7BmH328NKqIJNKCLsvSNe4NLnKWQMcBFydfVM5BUg+Erb6Qr/HCI4jsSziF1hg0VLIlPvC5T8I=}
bot:
  automerge: true
